[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]

targets = [
    # Linux
    "x86_64-unknown-linux-musl",
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "arm-unknown-linux-musleabi",
    "armv7-unknown-linux-musleabihf",
    # Windows
    "x86_64-pc-windows-gnu",
    # MacOS
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
]

profile = "minimal"
