// This file is generated by rust-protobuf 2.22.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `src/config/geosite.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_22_1;

#[derive(PartialEq,Clone,Default)]
pub struct Domain {
    // message fields
    pub field_type: Domain_Type,
    pub value: ::std::string::String,
    pub attribute: ::protobuf::RepeatedField<Domain_Attribute>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Domain {
    fn default() -> &'a Domain {
        <Domain as ::protobuf::Message>::default_instance()
    }
}

impl Domain {
    pub fn new() -> Domain {
        ::std::default::Default::default()
    }

    // .Domain.Type type = 1;


    pub fn get_field_type(&self) -> Domain_Type {
        self.field_type
    }
    pub fn clear_field_type(&mut self) {
        self.field_type = Domain_Type::Plain;
    }

    // Param is passed by value, moved
    pub fn set_field_type(&mut self, v: Domain_Type) {
        self.field_type = v;
    }

    // string value = 2;


    pub fn get_value(&self) -> &str {
        &self.value
    }
    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::string::String) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::string::String {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.value, ::std::string::String::new())
    }

    // repeated .Domain.Attribute attribute = 3;


    pub fn get_attribute(&self) -> &[Domain_Attribute] {
        &self.attribute
    }
    pub fn clear_attribute(&mut self) {
        self.attribute.clear();
    }

    // Param is passed by value, moved
    pub fn set_attribute(&mut self, v: ::protobuf::RepeatedField<Domain_Attribute>) {
        self.attribute = v;
    }

    // Mutable pointer to the field.
    pub fn mut_attribute(&mut self) -> &mut ::protobuf::RepeatedField<Domain_Attribute> {
        &mut self.attribute
    }

    // Take field
    pub fn take_attribute(&mut self) -> ::protobuf::RepeatedField<Domain_Attribute> {
        ::std::mem::replace(&mut self.attribute, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for Domain {
    fn is_initialized(&self) -> bool {
        for v in &self.attribute {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.field_type, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.value)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.attribute)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.field_type != Domain_Type::Plain {
            my_size += ::protobuf::rt::enum_size(1, self.field_type);
        }
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.value);
        }
        for value in &self.attribute {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.field_type != Domain_Type::Plain {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.field_type))?;
        }
        if !self.value.is_empty() {
            os.write_string(2, &self.value)?;
        }
        for v in &self.attribute {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Domain {
        Domain::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<Domain_Type>>(
                "type",
                |m: &Domain| { &m.field_type },
                |m: &mut Domain| { &mut m.field_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "value",
                |m: &Domain| { &m.value },
                |m: &mut Domain| { &mut m.value },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Domain_Attribute>>(
                "attribute",
                |m: &Domain| { &m.attribute },
                |m: &mut Domain| { &mut m.attribute },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Domain>(
                "Domain",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Domain {
        static instance: ::protobuf::rt::LazyV2<Domain> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Domain::new)
    }
}

impl ::protobuf::Clear for Domain {
    fn clear(&mut self) {
        self.field_type = Domain_Type::Plain;
        self.value.clear();
        self.attribute.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Domain {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Domain {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Domain_Attribute {
    // message fields
    pub key: ::std::string::String,
    // message oneof groups
    pub typed_value: ::std::option::Option<Domain_Attribute_oneof_typed_value>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Domain_Attribute {
    fn default() -> &'a Domain_Attribute {
        <Domain_Attribute as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum Domain_Attribute_oneof_typed_value {
    bool_value(bool),
    int_value(i64),
}

impl Domain_Attribute {
    pub fn new() -> Domain_Attribute {
        ::std::default::Default::default()
    }

    // string key = 1;


    pub fn get_key(&self) -> &str {
        &self.key
    }
    pub fn clear_key(&mut self) {
        self.key.clear();
    }

    // Param is passed by value, moved
    pub fn set_key(&mut self, v: ::std::string::String) {
        self.key = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_key(&mut self) -> &mut ::std::string::String {
        &mut self.key
    }

    // Take field
    pub fn take_key(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.key, ::std::string::String::new())
    }

    // bool bool_value = 2;


    pub fn get_bool_value(&self) -> bool {
        match self.typed_value {
            ::std::option::Option::Some(Domain_Attribute_oneof_typed_value::bool_value(v)) => v,
            _ => false,
        }
    }
    pub fn clear_bool_value(&mut self) {
        self.typed_value = ::std::option::Option::None;
    }

    pub fn has_bool_value(&self) -> bool {
        match self.typed_value {
            ::std::option::Option::Some(Domain_Attribute_oneof_typed_value::bool_value(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_bool_value(&mut self, v: bool) {
        self.typed_value = ::std::option::Option::Some(Domain_Attribute_oneof_typed_value::bool_value(v))
    }

    // int64 int_value = 3;


    pub fn get_int_value(&self) -> i64 {
        match self.typed_value {
            ::std::option::Option::Some(Domain_Attribute_oneof_typed_value::int_value(v)) => v,
            _ => 0,
        }
    }
    pub fn clear_int_value(&mut self) {
        self.typed_value = ::std::option::Option::None;
    }

    pub fn has_int_value(&self) -> bool {
        match self.typed_value {
            ::std::option::Option::Some(Domain_Attribute_oneof_typed_value::int_value(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_int_value(&mut self, v: i64) {
        self.typed_value = ::std::option::Option::Some(Domain_Attribute_oneof_typed_value::int_value(v))
    }
}

impl ::protobuf::Message for Domain_Attribute {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.key)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.typed_value = ::std::option::Option::Some(Domain_Attribute_oneof_typed_value::bool_value(is.read_bool()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.typed_value = ::std::option::Option::Some(Domain_Attribute_oneof_typed_value::int_value(is.read_int64()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.key);
        }
        if let ::std::option::Option::Some(ref v) = self.typed_value {
            match v {
                &Domain_Attribute_oneof_typed_value::bool_value(v) => {
                    my_size += 2;
                },
                &Domain_Attribute_oneof_typed_value::int_value(v) => {
                    my_size += ::protobuf::rt::value_size(3, v, ::protobuf::wire_format::WireTypeVarint);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.key.is_empty() {
            os.write_string(1, &self.key)?;
        }
        if let ::std::option::Option::Some(ref v) = self.typed_value {
            match v {
                &Domain_Attribute_oneof_typed_value::bool_value(v) => {
                    os.write_bool(2, v)?;
                },
                &Domain_Attribute_oneof_typed_value::int_value(v) => {
                    os.write_int64(3, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Domain_Attribute {
        Domain_Attribute::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "key",
                |m: &Domain_Attribute| { &m.key },
                |m: &mut Domain_Attribute| { &mut m.key },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_bool_accessor::<_>(
                "bool_value",
                Domain_Attribute::has_bool_value,
                Domain_Attribute::get_bool_value,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_i64_accessor::<_>(
                "int_value",
                Domain_Attribute::has_int_value,
                Domain_Attribute::get_int_value,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Domain_Attribute>(
                "Domain.Attribute",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Domain_Attribute {
        static instance: ::protobuf::rt::LazyV2<Domain_Attribute> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Domain_Attribute::new)
    }
}

impl ::protobuf::Clear for Domain_Attribute {
    fn clear(&mut self) {
        self.key.clear();
        self.typed_value = ::std::option::Option::None;
        self.typed_value = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Domain_Attribute {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Domain_Attribute {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum Domain_Type {
    Plain = 0,
    Regex = 1,
    Domain = 2,
    Full = 3,
}

impl ::protobuf::ProtobufEnum for Domain_Type {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Domain_Type> {
        match value {
            0 => ::std::option::Option::Some(Domain_Type::Plain),
            1 => ::std::option::Option::Some(Domain_Type::Regex),
            2 => ::std::option::Option::Some(Domain_Type::Domain),
            3 => ::std::option::Option::Some(Domain_Type::Full),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [Domain_Type] = &[
            Domain_Type::Plain,
            Domain_Type::Regex,
            Domain_Type::Domain,
            Domain_Type::Full,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<Domain_Type>("Domain.Type", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for Domain_Type {
}

impl ::std::default::Default for Domain_Type {
    fn default() -> Self {
        Domain_Type::Plain
    }
}

impl ::protobuf::reflect::ProtobufValue for Domain_Type {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct SiteGroup {
    // message fields
    pub tag: ::std::string::String,
    pub domain: ::protobuf::RepeatedField<Domain>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SiteGroup {
    fn default() -> &'a SiteGroup {
        <SiteGroup as ::protobuf::Message>::default_instance()
    }
}

impl SiteGroup {
    pub fn new() -> SiteGroup {
        ::std::default::Default::default()
    }

    // string tag = 1;


    pub fn get_tag(&self) -> &str {
        &self.tag
    }
    pub fn clear_tag(&mut self) {
        self.tag.clear();
    }

    // Param is passed by value, moved
    pub fn set_tag(&mut self, v: ::std::string::String) {
        self.tag = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_tag(&mut self) -> &mut ::std::string::String {
        &mut self.tag
    }

    // Take field
    pub fn take_tag(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.tag, ::std::string::String::new())
    }

    // repeated .Domain domain = 2;


    pub fn get_domain(&self) -> &[Domain] {
        &self.domain
    }
    pub fn clear_domain(&mut self) {
        self.domain.clear();
    }

    // Param is passed by value, moved
    pub fn set_domain(&mut self, v: ::protobuf::RepeatedField<Domain>) {
        self.domain = v;
    }

    // Mutable pointer to the field.
    pub fn mut_domain(&mut self) -> &mut ::protobuf::RepeatedField<Domain> {
        &mut self.domain
    }

    // Take field
    pub fn take_domain(&mut self) -> ::protobuf::RepeatedField<Domain> {
        ::std::mem::replace(&mut self.domain, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for SiteGroup {
    fn is_initialized(&self) -> bool {
        for v in &self.domain {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.tag)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.domain)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.tag.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.tag);
        }
        for value in &self.domain {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.tag.is_empty() {
            os.write_string(1, &self.tag)?;
        }
        for v in &self.domain {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SiteGroup {
        SiteGroup::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "tag",
                |m: &SiteGroup| { &m.tag },
                |m: &mut SiteGroup| { &mut m.tag },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Domain>>(
                "domain",
                |m: &SiteGroup| { &m.domain },
                |m: &mut SiteGroup| { &mut m.domain },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SiteGroup>(
                "SiteGroup",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SiteGroup {
        static instance: ::protobuf::rt::LazyV2<SiteGroup> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SiteGroup::new)
    }
}

impl ::protobuf::Clear for SiteGroup {
    fn clear(&mut self) {
        self.tag.clear();
        self.domain.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SiteGroup {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SiteGroup {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct SiteGroupList {
    // message fields
    pub site_group: ::protobuf::RepeatedField<SiteGroup>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SiteGroupList {
    fn default() -> &'a SiteGroupList {
        <SiteGroupList as ::protobuf::Message>::default_instance()
    }
}

impl SiteGroupList {
    pub fn new() -> SiteGroupList {
        ::std::default::Default::default()
    }

    // repeated .SiteGroup site_group = 1;


    pub fn get_site_group(&self) -> &[SiteGroup] {
        &self.site_group
    }
    pub fn clear_site_group(&mut self) {
        self.site_group.clear();
    }

    // Param is passed by value, moved
    pub fn set_site_group(&mut self, v: ::protobuf::RepeatedField<SiteGroup>) {
        self.site_group = v;
    }

    // Mutable pointer to the field.
    pub fn mut_site_group(&mut self) -> &mut ::protobuf::RepeatedField<SiteGroup> {
        &mut self.site_group
    }

    // Take field
    pub fn take_site_group(&mut self) -> ::protobuf::RepeatedField<SiteGroup> {
        ::std::mem::replace(&mut self.site_group, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for SiteGroupList {
    fn is_initialized(&self) -> bool {
        for v in &self.site_group {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.site_group)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.site_group {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.site_group {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SiteGroupList {
        SiteGroupList::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<SiteGroup>>(
                "site_group",
                |m: &SiteGroupList| { &m.site_group },
                |m: &mut SiteGroupList| { &mut m.site_group },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SiteGroupList>(
                "SiteGroupList",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SiteGroupList {
        static instance: ::protobuf::rt::LazyV2<SiteGroupList> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SiteGroupList::new)
    }
}

impl ::protobuf::Clear for SiteGroupList {
    fn clear(&mut self) {
        self.site_group.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SiteGroupList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SiteGroupList {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18src/config/geosite.proto\"\x93\x02\n\x06Domain\x12\x20\n\x04type\
    \x18\x01\x20\x01(\x0e2\x0c.Domain.TypeR\x04type\x12\x14\n\x05value\x18\
    \x02\x20\x01(\tR\x05value\x12/\n\tattribute\x18\x03\x20\x03(\x0b2\x11.Do\
    main.AttributeR\tattribute\x1al\n\tAttribute\x12\x10\n\x03key\x18\x01\
    \x20\x01(\tR\x03key\x12\x1f\n\nbool_value\x18\x02\x20\x01(\x08H\0R\tbool\
    Value\x12\x1d\n\tint_value\x18\x03\x20\x01(\x03H\0R\x08intValueB\r\n\x0b\
    typed_value\"2\n\x04Type\x12\t\n\x05Plain\x10\0\x12\t\n\x05Regex\x10\x01\
    \x12\n\n\x06Domain\x10\x02\x12\x08\n\x04Full\x10\x03\">\n\tSiteGroup\x12\
    \x10\n\x03tag\x18\x01\x20\x01(\tR\x03tag\x12\x1f\n\x06domain\x18\x02\x20\
    \x03(\x0b2\x07.DomainR\x06domain\":\n\rSiteGroupList\x12)\n\nsite_group\
    \x18\x01\x20\x03(\x0b2\n.SiteGroupR\tsiteGroupb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
