// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc 26.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `geosite.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

// @@protoc_insertion_point(message:Domain)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Domain {
    // message fields
    // @@protoc_insertion_point(field:Domain.type)
    pub type_: ::protobuf::EnumOrUnknown<domain::Type>,
    // @@protoc_insertion_point(field:Domain.value)
    pub value: ::std::string::String,
    // @@protoc_insertion_point(field:Domain.attribute)
    pub attribute: ::std::vec::Vec<domain::Attribute>,
    // special fields
    // @@protoc_insertion_point(special_field:Domain.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Domain {
    fn default() -> &'a Domain {
        <Domain as ::protobuf::Message>::default_instance()
    }
}

impl Domain {
    pub fn new() -> Domain {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for Domain {
    const NAME: &'static str = "Domain";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.value = is.read_string()?;
                },
                26 => {
                    self.attribute.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.type_ != ::protobuf::EnumOrUnknown::new(domain::Type::Plain) {
            my_size += ::protobuf::rt::int32_size(1, self.type_.value());
        }
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.value);
        }
        for value in &self.attribute {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.type_ != ::protobuf::EnumOrUnknown::new(domain::Type::Plain) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        if !self.value.is_empty() {
            os.write_string(2, &self.value)?;
        }
        for v in &self.attribute {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Domain {
        Domain::new()
    }

    fn clear(&mut self) {
        self.type_ = ::protobuf::EnumOrUnknown::new(domain::Type::Plain);
        self.value.clear();
        self.attribute.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Domain {
        static instance: Domain = Domain {
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            value: ::std::string::String::new(),
            attribute: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `Domain`
pub mod domain {
    // @@protoc_insertion_point(message:Domain.Attribute)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Attribute {
        // message fields
        // @@protoc_insertion_point(field:Domain.Attribute.key)
        pub key: ::std::string::String,
        // message oneof groups
        pub typed_value: ::std::option::Option<attribute::Typed_value>,
        // special fields
        // @@protoc_insertion_point(special_field:Domain.Attribute.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Attribute {
        fn default() -> &'a Attribute {
            <Attribute as ::protobuf::Message>::default_instance()
        }
    }

    impl Attribute {
        pub fn new() -> Attribute {
            ::std::default::Default::default()
        }

        // bool bool_value = 2;

        pub fn bool_value(&self) -> bool {
            match self.typed_value {
                ::std::option::Option::Some(attribute::Typed_value::BoolValue(v)) => v,
                _ => false,
            }
        }

        pub fn clear_bool_value(&mut self) {
            self.typed_value = ::std::option::Option::None;
        }

        pub fn has_bool_value(&self) -> bool {
            match self.typed_value {
                ::std::option::Option::Some(attribute::Typed_value::BoolValue(..)) => true,
                _ => false,
            }
        }

        // Param is passed by value, moved
        pub fn set_bool_value(&mut self, v: bool) {
            self.typed_value = ::std::option::Option::Some(attribute::Typed_value::BoolValue(v))
        }

        // int64 int_value = 3;

        pub fn int_value(&self) -> i64 {
            match self.typed_value {
                ::std::option::Option::Some(attribute::Typed_value::IntValue(v)) => v,
                _ => 0,
            }
        }

        pub fn clear_int_value(&mut self) {
            self.typed_value = ::std::option::Option::None;
        }

        pub fn has_int_value(&self) -> bool {
            match self.typed_value {
                ::std::option::Option::Some(attribute::Typed_value::IntValue(..)) => true,
                _ => false,
            }
        }

        // Param is passed by value, moved
        pub fn set_int_value(&mut self, v: i64) {
            self.typed_value = ::std::option::Option::Some(attribute::Typed_value::IntValue(v))
        }
    }

    impl ::protobuf::Message for Attribute {
        const NAME: &'static str = "Attribute";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.key = is.read_string()?;
                    },
                    16 => {
                        self.typed_value = ::std::option::Option::Some(attribute::Typed_value::BoolValue(is.read_bool()?));
                    },
                    24 => {
                        self.typed_value = ::std::option::Option::Some(attribute::Typed_value::IntValue(is.read_int64()?));
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.key.is_empty() {
                my_size += ::protobuf::rt::string_size(1, &self.key);
            }
            if let ::std::option::Option::Some(ref v) = self.typed_value {
                match v {
                    &attribute::Typed_value::BoolValue(v) => {
                        my_size += 1 + 1;
                    },
                    &attribute::Typed_value::IntValue(v) => {
                        my_size += ::protobuf::rt::int64_size(3, v);
                    },
                };
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.key.is_empty() {
                os.write_string(1, &self.key)?;
            }
            if let ::std::option::Option::Some(ref v) = self.typed_value {
                match v {
                    &attribute::Typed_value::BoolValue(v) => {
                        os.write_bool(2, v)?;
                    },
                    &attribute::Typed_value::IntValue(v) => {
                        os.write_int64(3, v)?;
                    },
                };
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Attribute {
            Attribute::new()
        }

        fn clear(&mut self) {
            self.key.clear();
            self.typed_value = ::std::option::Option::None;
            self.typed_value = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Attribute {
            static instance: Attribute = Attribute {
                key: ::std::string::String::new(),
                typed_value: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    /// Nested message and enums of message `Attribute`
    pub mod attribute {

        #[derive(Clone,PartialEq,Debug)]
        #[non_exhaustive]
        // @@protoc_insertion_point(oneof:Domain.Attribute.typed_value)
        pub enum Typed_value {
            // @@protoc_insertion_point(oneof_field:Domain.Attribute.bool_value)
            BoolValue(bool),
            // @@protoc_insertion_point(oneof_field:Domain.Attribute.int_value)
            IntValue(i64),
        }

        impl ::protobuf::Oneof for Typed_value {
        }

        impl Typed_value {
        }
    }

    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:Domain.Type)
    pub enum Type {
        // @@protoc_insertion_point(enum_value:Domain.Type.Plain)
        Plain = 0,
        // @@protoc_insertion_point(enum_value:Domain.Type.Regex)
        Regex = 1,
        // @@protoc_insertion_point(enum_value:Domain.Type.Domain)
        Domain = 2,
        // @@protoc_insertion_point(enum_value:Domain.Type.Full)
        Full = 3,
    }

    impl ::protobuf::Enum for Type {
        const NAME: &'static str = "Type";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Type> {
            match value {
                0 => ::std::option::Option::Some(Type::Plain),
                1 => ::std::option::Option::Some(Type::Regex),
                2 => ::std::option::Option::Some(Type::Domain),
                3 => ::std::option::Option::Some(Type::Full),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<Type> {
            match str {
                "Plain" => ::std::option::Option::Some(Type::Plain),
                "Regex" => ::std::option::Option::Some(Type::Regex),
                "Domain" => ::std::option::Option::Some(Type::Domain),
                "Full" => ::std::option::Option::Some(Type::Full),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Type] = &[
            Type::Plain,
            Type::Regex,
            Type::Domain,
            Type::Full,
        ];
    }

    impl ::std::default::Default for Type {
        fn default() -> Self {
            Type::Plain
        }
    }

}

// @@protoc_insertion_point(message:SiteGroup)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SiteGroup {
    // message fields
    // @@protoc_insertion_point(field:SiteGroup.tag)
    pub tag: ::std::string::String,
    // @@protoc_insertion_point(field:SiteGroup.domain)
    pub domain: ::std::vec::Vec<Domain>,
    // special fields
    // @@protoc_insertion_point(special_field:SiteGroup.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SiteGroup {
    fn default() -> &'a SiteGroup {
        <SiteGroup as ::protobuf::Message>::default_instance()
    }
}

impl SiteGroup {
    pub fn new() -> SiteGroup {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for SiteGroup {
    const NAME: &'static str = "SiteGroup";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.tag = is.read_string()?;
                },
                18 => {
                    self.domain.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.tag.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.tag);
        }
        for value in &self.domain {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.tag.is_empty() {
            os.write_string(1, &self.tag)?;
        }
        for v in &self.domain {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SiteGroup {
        SiteGroup::new()
    }

    fn clear(&mut self) {
        self.tag.clear();
        self.domain.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SiteGroup {
        static instance: SiteGroup = SiteGroup {
            tag: ::std::string::String::new(),
            domain: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

// @@protoc_insertion_point(message:SiteGroupList)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SiteGroupList {
    // message fields
    // @@protoc_insertion_point(field:SiteGroupList.site_group)
    pub site_group: ::std::vec::Vec<SiteGroup>,
    // special fields
    // @@protoc_insertion_point(special_field:SiteGroupList.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SiteGroupList {
    fn default() -> &'a SiteGroupList {
        <SiteGroupList as ::protobuf::Message>::default_instance()
    }
}

impl SiteGroupList {
    pub fn new() -> SiteGroupList {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for SiteGroupList {
    const NAME: &'static str = "SiteGroupList";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.site_group.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.site_group {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.site_group {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SiteGroupList {
        SiteGroupList::new()
    }

    fn clear(&mut self) {
        self.site_group.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SiteGroupList {
        static instance: SiteGroupList = SiteGroupList {
            site_group: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}
