[package]
name = "leaf-ffi"
version = "0.1.0"
authors = ["eycorsican <eric.y.corsican@gmail.com>"]
edition = "2021"

[lib]
name = "leaf"
path = "src/lib.rs"
crate-type = ["staticlib", "dylib"]

[features]
default = [
    "default-aws-lc",
    "auto-reload",
]

default-aws-lc= [
    "leaf/default-aws-lc",
]

default-ring = [
    "leaf/default-ring",
]

default-openssl = [
    "leaf/default-openssl",
]

auto-reload = ["leaf/auto-reload"]

plugin = ["leaf/plugin"]
# Adds downloading plugins by url to the start, and leaf_prefetch_plugins.
plugin-fetch = ["plugin", "leaf/plugin-fetch"]

[dependencies]
leaf = { path = "../leaf", default-features = false, optional = true }
tokio = { version = "1", features = ["rt"] }
anyhow = "1.0"
futures = "0.3"

[dev-dependencies]
sha2 = "0.10"
